// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCguUzXzPWOAh-iQojTjLTgS2ezXKtyp_s',
    appId: '1:584490896456:web:c52128e82dc352ac535c7d',
    messagingSenderId: '584490896456',
    projectId: 'quiz-zentrale',
    authDomain: 'quiz-zentrale.firebaseapp.com',
    storageBucket: 'quiz-zentrale.appspot.com',
    measurementId: 'G-PCFSFBVXP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNGsAU2UYpL36DFmBNUt4Twyx5VsTLzXk',
    appId: '1:584490896456:android:8653f4abfc353e07535c7d',
    messagingSenderId: '584490896456',
    projectId: 'quiz-zentrale',
    storageBucket: 'quiz-zentrale.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcmKZLiY1HZcnf54ITavhN8aoPV5fgrQ0',
    appId: '1:584490896456:ios:e411868dcc6fd2ba535c7d',
    messagingSenderId: '584490896456',
    projectId: 'quiz-zentrale',
    storageBucket: 'quiz-zentrale.appspot.com',
    iosBundleId: 'com.diedu.quizzly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcmKZLiY1HZcnf54ITavhN8aoPV5fgrQ0',
    appId: '1:584490896456:ios:e411868dcc6fd2ba535c7d',
    messagingSenderId: '584490896456',
    projectId: 'quiz-zentrale',
    storageBucket: 'quiz-zentrale.appspot.com',
    iosBundleId: 'com.diedu.quizzly',
  );
}
